Modulo_Residencias/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views 
from django.urls import path, include
from proyecto_usuario.views import registro_usuario,registro_proyecto
from modulo_comunicacion.views import base, mensajes_directos

from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico/', RedirectView.as_view(url='/static/img/favicon/favicon.ico')),
    path('canales/', include('modulo_comunicacion.urls')),
    path('', base, name='index'),
    path('<str:username>', mensajes_directos, name='msg'),
    path('registro_usuario/', registro_usuario, name='registro_usuario' ),
    path('registro_proyecto/', registro_proyecto, name='registro_proyecto' ),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login' ),
    path('logout/', auth_views.LogoutView.as_view(), name='logout' ),
]

modulo_comunicacion/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView


urlpatterns = [
    path('favicon.ico/', RedirectView.as_view(url='/static/img/favicon/favicon.ico')),
    path('', views.CanalesAltas, name='canales' ),
    path('<slug:slug>', views.CanalVista, name='canalesVista' ),
]

modulo_comunicacion/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User
from proyecto_usuario.models import registro_proyecto

class Canal_Comunicacion(models.Model):
    estatus_choice = (
        ("ABIERTO", "Abierto"), 
        ("CERRADO", "Cerrado"), 
    )
    nombrecanal = models.CharField(max_length=25)
    fecha_crecion_canal = models.DateTimeField(default=datetime.now, blank=True)
    estatus_canal = models.CharField(max_length=15, choices=estatus_choice, default="Abierto")
    slug = models.SlugField(unique=True)
    fk_proyecto = models.ForeignKey(registro_proyecto, on_delete=models.CASCADE)
    fk_usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombrecanal

    class Meta:
        db_table = 'Canal_Comunicacion'
        verbose_name = 'Canal_Comunicacion'
        verbose_name_plural = 'Canales_Comunicacion'

class Mensajes_canal(models.Model):
    canal = models.ForeignKey(Canal_Comunicacion, related_name='mensajesCanal', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='mensajesCanal', on_delete=models.CASCADE)
    contenido = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date_added',)

class Archivos (models.Model):
    mensajes_canal = models.ForeignKey(Mensajes_canal, on_delete=models.CASCADE)
    file = models.FileField(upload_to='archivos/canales')

    class Meta:
        db_table = 'Arhivos'
        verbose_name = 'Archivo'
        verbose_name_plural = 'Archivos'

class MensajePrivados (models.Model):
    sender = models.CharField(max_length=100, default=None)
    message = models.TextField(null=True, blank=True)
    thread_name = models.CharField(null=True, blank=True, max_length=50)
    timestamp = models.DateTimeField(auto_now_add=True, null=True)
    archivopriv= models.FileField(upload_to='media/',  blank=False, null=True)

    def __str__(self):
        return self.message

class Archivoprivado (models.Model):
    thread_name = models.CharField(null=True, blank=True, max_length=50)
    filepriv = models.FileField(upload_to='archivos/privados', blank=False, null=True)

class Archivopublico (models.Model):
    
    filegroup = models.FileField(upload_to='archivos/grupales', blank=False, null=True)

modulo_comunicacion/forms.py
from django.forms import ModelForm
from django import forms
from .models import Canal_Comunicacion

class anadirCanalForm(ModelForm):           
    class Meta:
        model = Canal_Comunicacion
        fields = ['nombrecanal', 'estatus_canal', 'slug', 'fk_proyecto', 'fk_usuario']
        help_texts = {k:"" for k in fields}

class archivopriv (forms.Form):
    file = forms.FileField()

class archivogrupal (forms.Form):
    file = forms.FileField()

modulo_comunicacion/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.contrib.auth import get_user_model
from django.http import HttpResponse

User = get_user_model()

from .models import Canal_Comunicacion, Mensajes_canal, Archivopublico, Archivoprivado, MensajePrivados
from proyecto_usuario.models import registro_proyecto

from .forms import anadirCanalForm, archivopriv, archivogrupal

# --------------Vista de usuarios (mensajes directos)------------------------
def base (request):
    users = User.objects.exclude(username=request.user.username)
    return render(request, 'index.html', {'users': users})
    
# -------------------------mensajes directo vista y funcionalidad-----------------------
def mensajes_directos (request, username):
    user_obj = User.objects.get(username=username)
    users = User.objects.exclude(username=request.user.username)

# ---------------Subir archivo----------------
    if request.method == 'POST':
        archivonew = archivopriv(request.POST, request.FILES)
        file = request.FILES['file']
        filenew = Archivoprivado.objects.create(filepriv=file)
        filenew.save()
        
    else:
        archivonew= archivopriv()
# ---------------------------

    if request.user.id > user_obj.id:
        thread_name = f'chat_{request.user.id}-{user_obj.id}'
    else:
        thread_name = f'chat_{user_obj.id}-{request.user.id}'
        print(thread_name)
    messaje_obj = MensajePrivados.objects.filter(thread_name=thread_name)
    return render(request, 'mensajes_direct.html', {'users': users, 'user_obj':user_obj, 'archivonew':archivonew, 'files':Archivoprivado.objects.all(), 'messages':messaje_obj})

@login_required
def CanalesAltas(request):
    canales = Canal_Comunicacion.objects.all()
    crearcanal = anadirCanalForm()
    if request.method == 'POST':
        crearcanal = anadirCanalForm(request.POST)
        if crearcanal.is_valid():
            crearcanal.save()
        else:
            crearcanal = anadirCanalForm()
    return render(request, 'canales.html', {'canales': canales, 'crearcanal':crearcanal, 'usuarios':User.objects.all(), 'proyectos':registro_proyecto.objects.all()})

@login_required
def CanalVista(request, slug):
    vistaCanal = Canal_Comunicacion.objects.get(slug=slug)
    mensajesenviados = Mensajes_canal.objects.filter(canal=vistaCanal)[0:25]
    return render(request, 'vista_canal.html', {'vistaCanal': vistaCanal,'mensajesenviados':mensajesenviados})

modulo_comunicacion/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %} Modulo Comunicacion </title>
    <script src="https://cdn.tailwindcss.com"></script>
    {% if request.user.is_authenticated %}
    <style>
        .chat-messages {
            height: 400px;
            overflow-y: auto;
        }

        .titulo_mensdi {
            padding-bottom: 15px;
        }

        .mensajesdirectos {
            width: 300px;
            height: 649px;
            color: #ffffff;
            font-size: 1.2rem;
            background-color: #323232;
            padding-top: 30px;
            text-align: center;
        }

        .contedorpriv {
            display: flex;
        }

        .usuarioslink {
            color: yellow;
            display: block;
            padding: 10px;
        }

        .usuarioslink:hover {
            background-color: #1E1E1E;
        }

        .file-select {
            position: relative;
            display: inline-block;
            margin-left: 10PX;
            margin-right: 10px;
            cursor: pointer;
        }

        .file-select::before {
            background-color: #336b67;
            color: white;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 3px;
            content: 'Seleccinar archivo';
            position: absolute;
            left: 0;
            right: 0;
            top: 0;
            bottom: 0;
            cursor: pointer;
        }

        .file-select input[type="file"] {
            opacity: 0;
            width: 200px;
            height: 32px;
            display: inline-block;
            cursor: pointer;
        }

        .contenedorchat {
            display: flex;
        }
    </style>
    {%endif%}
    <style>
        .contenedor_msg {
            background-color: #ffffff;
            width: 854px;
            padding: 15px;
            display: flex;
        }

        .contenedorMensj {
            padding-left: 25px;
        }

        .mensajesDir {
            height: 450px;
            width: 850px;
            margin-left: 25px;
            margin-bottom: 0px;
            background-color: #ffffff;
        }
    </style>
</head>

<body class="bg-neutral-600">
    <nav class="flex items-center justify-between px-4 py-6 bg-neutral-900">
        <div>
            <a href="{%url 'index'%}" class="text-lg text-white">Modulo Comunicacion</a>
        </div>
        <div class="flex items-center space-x-4">
            {% if request.user.is_authenticated %}
            <!-- <a href="/registro_proyecto/" class="text-white hover:text-orange-300">Registrar proyecto</a> -->
            <a href="/canales/" class="px-5 py-3 rounded-xl text-white bg-neutral-800 hover:bg-neutral-700">Canales</a>
            <a href="/logout/" class="px-5 py-3 rounded-xl text-white bg-neutral-800 hover:bg-neutral-700">Salir</a>
            {% else %}

            <a href="/login/" class="text-white hover:text-orange-300">Login</a>
            <a href="/registro_usuario/"
                class="px-5 py-3 rounded-xl text-white bg-neutral-800 hover:bg-neutral-700">Registro</a>
            {%endif%}
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    {% block scripts %}
    {% endblock %}
</body>

</html>

modulo_comunicacion/templates/canales.html
{% extends 'base.html' %}

{% block title %} Canales | {% endblock %}

{% block content %}
<style>
    .boton_anadiscanales {
        margin-top: 40px;
        margin-left: 95%;
        margin-bottom: -40px;
    }

    .lbl-modal {
        color: #FFFFFF;
        padding: 5px 8px;
        font-size: 30px;
        background-color: #262626;
        border-radius: 5px;
        cursor: pointer;
    }

    .lbl-modal:hover {
        background-color: #404040;
    }

    .cerrar {
        color: #FFFFFF;
        padding: 2px 10px;
        margin-left: 95%;
        font-size: 20px;
        background-color: #3C4043;
        border-radius: 5px;
        cursor: pointer;
    }

    .cerrar:hover {
        background-color: #4a5053;
    }

    .modal {
        width: 100%;
        height: 100vh;
        display: flex;
        justify-content: center;
        align-items: center;
        position: fixed;
        top: 0;
        left: 0;
        background-color: rgba(0, 0, 0, 0.5);
        transition: all 500ms ease;
        opacity: 0;
        visibility: hidden;
    }

    #btn-modal:checked~.modal {
        opacity: 1;
        visibility: visible;
    }

    .caja {
        width: 500px;
        height: 500px;
        margin: auto;
        background-color: #1E1E1E;
        border-radius: 15px;
        transition: all 500ms ease;
        position: relative;
        transform: translateY(-30%);
    }

    #btn-modal:checked~.modal .caja {
        transform: translateY(0%);
    }

    #btn-modal {
        display: none;
    }
</style>
<div class="boton_anadiscanales">
    <input type="checkbox" id="btn-modal"><label for="btn-modal" class="lbl-modal">✚</label>
    <div class="modal">
        <div class="caja overflow-auto flex-initial w-700 p-10 lg:p-20">
            <label class="cerrar" for="btn-modal">✘</label>
            <h1 class="text-3xl text-white text-center">Añadir canal</h1>
            <form method="post" action="">
                {%csrf_token%}
                <div class="mb-5">
                    <label class="text-lg text-white" for="id_nombrecanal">Nombre del canal: </label>
                    <input type="tex" name="nombrecanal" class="w-full mt-2 px-4 py-2 rounded-xl" required
                        id="id_nombrecanal">
                </div>
                <div class="mb-5">
                    <label class="text-lg text-white" for="id_estatus_canal">Estatus canal: </label>
                    <select name="estatus_canal" class="w-full mt-2 px-4 py-2 rounded-xl" id="id_estatus_canal">
                        <option value="ABIERTO">Abierto</option>
                        <option value="CERRADO">Cerrado</option>                      
                    </select>
                </div>
                <div class="mb-5">
                    <label class="text-lg text-white" for="id_slug">Url canal: </label>
                    <input type="text" name="slug" required class="w-full mt-2 px-4 py-2 rounded-xl" required
                        id="id_slug" placeholder="Abreviatura para su canal...">
                </div>
                <div class="mb-5">
                    <label class="text-lg text-white" for="id_slug">Proyecto(en que proyecto se añade): </label>
                    <select type="text" name="fk_proyecto" required class="w-full mt-2 px-4 py-2 rounded-xl" required>
                        {%for proyecto in proyectos%}
                        <option value="{{proyecto.idproyecto}}">{{proyecto.nombreproyecto}}</option>
                        {%endfor%}
                    </select>
                </div>
                <div class="mb-5">
                    <label class="text-lg text-white" for="id_fk_usuario">Usuario(quien crea el canal): </label>
                    <select type="text" name="fk_usuario" required class="w-full mt-2 px-4 py-2 rounded-xl" required>
                        {%for usuario in usuarios%}
                        <option value="{{usuario.id}}" selected="{{request.user.username}}">{{usuario.username}}</option>
                        {%endfor%}
                    </select>
                </div>
                <button class="botoncrear px-5 py-3 rounded-xl text-white bg-lime-700 hover:bg-lime-600"
                    type="submit">Crear canal</button>
            </form>
        </div>
    </div>
</div>
<!-- ----------------------------------------- -->
<div class="flex-initial w-700 p-10 lg:p-10 text-center">
    <h1 class="text-3xl lg:text-6xl text-white"><br>Canales</h1>
</div>
<div class="w-full flex flex-wrap items-center">
    {% for canal in canales %}
    <div class="w-full lg:w-1/4 px-3 py-3">
        <div class="p-4 bg-white shadow rounded-xl text-center">
            <h2 class="mb-5 text-2xl font-simibold"> # {{ canal.nombrecanal }}</h2>
            <a href="{% url 'canalesVista' canal.slug %}"
                class="px-5 py-3 block rounded-xl text-white bg-neutral-800 hover:bg-neutral-700">Unirse</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

modulo_comunicacion/templates/index.html
{% extends 'base.html' %}

{% block title %} Index | {% endblock %}

{% block content %}
<div class="contenedorchat">
    {% if request.user.is_authenticated %}
    <div class="mensajesdirectos">
        <p class="titulo_mensdi">Mensajes directos</p>
        {% for user in users %}
        <a class="usuarioslink" href="{% url 'msg' username=user.username %}">{{user.username}}</a>
        {% endfor %}
    </div>
    {%endif%}
    <div class="flex-initial w-700 p-10 lg:p-20 text-center">
        {% if request.user.is_authenticated %}
        <p class="text-3xl text-white">¡Hola {{ request.user.username | upper }}, bienvenid@!</p>
        {%endif%}
        <h1 class="text-3xl lg:text-6xl text-white"><br> Modulo de comunicacion <br>(Residencias)</h1>
    </div>
</div>


{% endblock %}

modulo_comunicacion/templates/mensajes_direct.html
{% extends 'base.html' %}

{% block title %} Mensajes | {% endblock %}

{% block content %}
<div class="contedorpriv">
    {% if request.user.is_authenticated %}
    <div class="mensajesdirectos">
        <div class="text-center">
            <p class="text-3xl lg:text-2xl text-white">- {{request.user.username}} -</p><br>
        </div>
        <p class="titulo_mensdi">Mensajes directos</p>
        {% for user in users %}
        <a class="usuarioslink" href="{% url 'msg' username=user.username %}">{{user.username}}</a>
        {% endfor %}
    </div>
    {%endif%}
    <div class="flex-auto w-700">
        <div class="flex-initial w-700 p-10 lg:p-4 text-left">
            <h1 class="text-3xl lg:text-4xl text-white"># {{user_obj.username}}</h1><br>
        </div>
        <div class="lg:w-2/3 mx-4 lg:mx-auto p-4 bg-white rounded-xl">

            <div class="chat-messages space-y-3" id="chat-body">
                {%for message in messages%}
                {% if message.sender == request.user.username %}
                <div class="p-4 m-0 bg-gray-400 rounded-xl">
                    <p> {{ message.sender}}</p>
                    <p> {{ message.message }}</p>
                </div>
                {% else %}
                <div class="p-4 m-0 bg-gray-200 rounded-xl">
                    <p> {{ message.sender}}</p>
                    <p> {{ message.message }}</p>
                </div>
                {% endif %}
                {%endfor%}

                {%for file in files%}
                <div class="p-4 m-0 bg-gray-400 rounded-xl">
                    <a href="{{file.filepriv.url}}" target="_blank">Descargar - {{ file.filepriv.name }}</a>
                </div>
                {%endfor%}
            </div>
        </div>
        <div class="lg:w-2/3 mt-6 mx-4 lg:mx-auto p-4 bg-white rounded.xl">
            <form method="post" class="flex" enctype="multipart/form-data">
                {%csrf_token%}
                <input type="text" name="content" class="flex-1 mr-3" placeholder="Escribe tu mensaje..."
                    id="chat-privado-input">
                <button class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700" type="submit"
                    value="upload" id="chat-privado-enviar">Enviar</button>

                <div class="file-select"><input name="file" type="file" required id="id_file"></div>
                <button class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700" type="submit"
                    value="upload" id="chat-privado-enviar">Subir</button>


            </form>
        </div>
    </div>
</div>

{{user_obj.id|json_script:"json-username"}}
{{request.user.username|json_script:"json-message-username"}}
{% endblock %}

{% block scripts %}
<script>
    const id = JSON.parse(document.getElementById('json-username').textContent);
    const message_username = JSON.parse(document.getElementById('json-message-username').textContent);

    const socket = new WebSocket(
        'ws://'
        + window.location.host
        + '/msg/'
        + id
        + '/'
    );
    socket.onopen = function (e) {
        console.log('CONECTADO');
    }
    socket.onclose = function (e) {
        console.log('DESCONECTADO');
    }
    socket.onerror = function (e) {
        console.log(e);
    }
    function scrollBottom() {
        let msgbox = document.querySelector("chat-body")
        msgbox.scrollTop = msgbox.scrollHeight
    }
    socket.onmessage = function (e) {
        const data = JSON.parse(e.data);
        if (data.username == message_username) {
            let html = '<div class="p-4 m-0 bg-gray-400 rounded-xl">';
            html += '<p class="font-semiblold">' + data.username + '</p>';
            html += '<p>' + data.message + '</p></div>';
            document.querySelector('#chat-body').innerHTML += html;
            scrollBottom();
        } else {
            let html = '<div class="p-4 m-0 bg-gray-200 rounded-xl">';
            html += '<p class="font-semiblold">' + data.username + '</p>';
            html += '<p>' + data.message + '</p></div>';
            document.querySelector('#chat-body').innerHTML += html;
            scrollBottom();
        }
    };

    document.querySelector('#chat-privado-enviar').onclick = function (e) {
        e.preventDefault();
        const message_input = document.querySelector('#chat-privado-input');
        const message = message_input.value;

        socket.send(JSON.stringify({
            'message': message,
            'username': message_username,
        }));
        message_input.value = '';
        return false;
    }


</script>
{% endblock %}

modulo_comunicacion/templates/vista_canal.html
{% extends 'base.html' %}

{% block title %} {{ vistaCanal.nombrecanal }} | {% endblock %}

{% block content %}
<div class="flex-initial w-700 p-10 lg:p-5 text-center">
    <h1 class="text-3xl lg:text-4xl text-white"># {{ vistaCanal.nombrecanal }}</h1>
</div>

<div class="lg:w-2/4 mx-4 lg:mx-auto p-4 bg-white rounded-xl">
    <div class="chat-messages space-y-3" id="chat-mensajes">
        {%for message in mensajesenviados%}
        <div class="p-4 bg-gray-200 rounded-xl">
            <p class="font-semiblold"> {{ message.user.username }}</p>
            <p> {{ message.contenido }}</p>
        </div>
        {%endfor%}
    </div>
</div>
<div class="lg:w-2/4 mt-6 mx-4 lg:mx-auto p-4 bg-white rounded.xl">
    <form method="POST" class="flex" enctype="multipart/form-data">
        {%csrf_token%}
        <input type="text" name="content" class="flex-1 mr-3" placeholder="Escribe tu mensaje..."
            id="chat-mensaje-input">
        <button class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700" type="submit" value="upload"
            id="chat-mensaje-enviar">Enviar</button>
        <div class="file-select"><input name="file" type="file" required id="id_file"></div>
        <!-- <button class="px-5 py-3 rounded-xl text-white bg-teal-600 hover:bg-teal-700" type="submit" value="upload"
            id="chat-privado-enviar">Subir</button> -->
    </form>
</div>
{% endblock %}

{% block scripts %}
{{ vistaCanal.slug|json_script:"json-canalnombre" }}
{{ request.user.username|json_script:"json-username" }}

<script>
    const canalNombre = JSON.parse(document.getElementById('json-canalnombre').textContent);
    const userNombre = JSON.parse(document.getElementById('json-username').textContent);
    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/'
        + canalNombre
        + '/'
    );

    chatSocket.onmessage = function (e) {
        console.log('onmessage')
        const data = JSON.parse(e.data);
        if (data.messege) {
            let html = '<div class="p-4 bg-gray-200 rounded-xl">';
            html += '<p class="font-semiblold">' + data.usernombre + '</p>';
            html += '<p>' + data.messege + '</p></div>';
            document.querySelector('#chat-mensajes').innerHTML += html;
        } else {
            alert('El menseje no salio!');
        }
    }
    chatSocket.onclose = function (e) {
        console.log('onclose')
    }

    //
    document.querySelector('#chat-mensaje-enviar').onclick = function (e) {
        e.preventDefault();
        const messageInputDom = document.querySelector('#chat-mensaje-input');
        const mensajeescrito = messageInputDom.value;

        chatSocket.send(JSON.stringify({
            'messege': mensajeescrito,
            'usernombre': userNombre,
            'canal': canalNombre,
        }));
        messageInputDom.value = '';
        return false;
    }

</script>
{% endblock %}