Modulo_Residencias/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views 
from django.urls import path, include
from proyecto_usuario.views import registro_usuario,registro_proyecto
from modulo_comunicacion.views import base, mensajes_directos

from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('favicon.ico/', RedirectView.as_view(url='/static/img/favicon/favicon.ico')),
    path('canales/', include('modulo_comunicacion.urls')),
    path('', base, name='index'),
    path('<str:username>', mensajes_directos, name='msg'),
    path('registro_usuario/', registro_usuario, name='registro_usuario' ),
    path('registro_proyecto/', registro_proyecto, name='registro_proyecto' ),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login' ),
    path('logout/', auth_views.LogoutView.as_view(), name='logout' ),
]

proyecto_usuario/models.py
from django.db import models
from django.contrib.auth.models import User

class registro_proyecto(models.Model):
    idproyecto = models.AutoField(primary_key=True, db_index=True, editable=False)
    nombreproyecto = models.CharField( blank = True, max_length = 50, null = False)
    descripcionProyecto = models.CharField(max_length= 80, null = True)
    fechaincio = models.DateTimeField(auto_now_add=True)
    fk_user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
            db_table = 'Proyecto'
            verbose_name = 'Proyecto'
            verbose_name_plural = 'Proyectos'

    def __str__(self):
        return  self.nombreproyecto

class conexionuser_proyec(models.Model):
    fk_proyecto = models.ForeignKey(registro_proyecto, on_delete=models.CASCADE)
    fk_user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'Conexion'
        verbose_name = 'conexion'
        verbose_name_plural = 'conexiones'

proyecto_usuario/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import registro_proyecto

class registro_usuarioForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        help_texts = {k:"" for k in fields}

class registro_proyectoForm (ModelForm):
     nombreproyecto = forms.CharField(label='Nombre proyecto', max_length = 50)
     descripcionProyecto = forms.CharField(label='Descripcion proyecto', max_length= 80, widget=forms.Textarea)

     class Meta:
        model = registro_proyecto
        fields = ['nombreproyecto', 'descripcionProyecto', 'fk_user']

proyecto_usuario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login

from .forms import registro_usuarioForm, registro_proyectoForm

def registro_usuario(request):
    if request.method == 'POST':
        registro_altausuario = registro_usuarioForm(request.POST)
        if registro_altausuario.is_valid():
            usuario = registro_altausuario.save()
            login(request, usuario)
            return redirect('/')
    else:
        registro_altausuario = registro_usuarioForm()
    return render(request, 'registro_usuario.html', {'registro_altausuario':registro_altausuario})

def registro_proyecto (request):
    if request.method == 'POST':
        registro_proyectoAlta = registro_proyectoForm (request.POST)
        if registro_proyectoAlta.is_valid():
            registro_proyectoAlta.save()
            return redirect('/')
    else:
        nuevo_usuario = registro_proyectoForm()
        registro_proyectoAlta = registro_proyectoForm()
    return render(request, 'registro_proyecto.html', {'registro_proyectoAlta': registro_proyectoAlta})   

proyecto_usuario/templates/login.html
{% extends 'base.html' %}

{% block title %} Login | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-3xl text-white">Login</h1>
</div>
<form method="POST" action="." class="lg:w-1/4 px-4 mx-auto">
    {%csrf_token%}
    <div class="mb-5">
        <label class="text-lg text-white">Nombre de usuario: </label>
        <input type="tex" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>
    <div class="mb-5">
        <label class="text-lg text-white">Contraseña: </label>
        <input type="password" name="password" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>
    {% if registro_altausuario.errors %}
        {% for field in registro_altausuario %}
            {% for error in field.errors %}
                <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
                    <p>{{ error|escape }}</p>
                </div>
            {%endfor%}
        {%endfor%}
    {%endif%}

    <button class="px-5 py-3 rounded-xl text-white bg-lime-700 hover:bg-lime-600" type="submit">Login</button>
</form>
{% endblock %}

proyecto_usuario/templates/registro_proyecto.html
{% extends 'base.html' %}

{% block title %} Registro proyecto | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-3xl text-white">Registro proyecto</h1>
</div>
<form method="POST" action="." class="lg:w-1/4 px-4 mx-auto">
    {%csrf_token%}
    <div class="mb-5">
        <label for="id_nombreproyecto" class="text-lg text-white">Nombre de proyecto: </label>
        <input type="tex" name="nombreproyecto" required id="id_nombreproyecto"
            class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>

    <div class="mb-5">
        <label for="id_descripcionProyecto" class="text-lg text-white">Descripcion proyecto: </label>
        <textarea type="tex" name="descripcionProyecto" required id="id_descripcionProyecto"
            class="w-full mt-2 px-4 py-2 rounded-xl"></textarea>
    </div>

    <div class="mb-5">
        <label for="id_fk_user" class="text-lg text-white">Usuario: </label>
        <select type="tex" name="fk_user" required id="id_fk_user" class="w-full mt-2 px-4 py-2 rounded-xl">
        <option value="" selected>Admin</option>
        <option value="14">Maria</option>
        <option value="16">Oliverio</option>
        <option value="2">Stefan</option>
        <option value="1">Admin</option>
        </select>
    </div>
    <button class="px-5 py-3 rounded-xl text-white bg-lime-700 hover:bg-lime-600" type="submit">Registrarse</button>
</form>
{% endblock %}

proyecto_usuario/templates/registro_usuario.html
{% extends 'base.html' %}

{% block title %} Registro | {% endblock %}

{% block content %}
<div class="p-10 lg:p-20 text-center">
    <h1 class="text-3xl lg:text-3xl text-white">Registro usuario</h1>
</div>
<form method="POST" action="." class="lg:w-1/4 px-4 mx-auto">
    {%csrf_token%}
    <div class="mb-5">
        <label class="text-lg text-white">Nombre de usuario: </label>
        <input type="tex" name="username" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>
    <div class="mb-5">
        <label class="text-lg text-white">Contraseña: </label>
        <input type="password" name="password1" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>
    <div class="mb-5">
        <label class="text-lg text-white">Confirme su contraseña: </label>
        <input type="password" name="password2" class="w-full mt-2 px-4 py-2 rounded-xl">
    </div>
    {% if registro_altausuario.errors %}
        {% for field in registro_altausuario %}
            {% for error in field.errors %}
                <div class="mb-5 p-4 rounded-xl bg-red-300 text-white">
                    <p>{{ error|escape }}</p>
                </div>
            {%endfor%}
        {%endfor%}
    {%endif%}

    <button class="px-5 py-3 rounded-xl text-white bg-lime-700 hover:bg-lime-600" type="submit">Registrarse</button>
</form>
{% endblock %}